### ISSUE TITLE
Why not...

### ISSUE THREAD

**Issue by robsonsobral** [cloudfour/transition-hidden-element#93]
As I can't comment on the article, let me suggest here.

The styles for the hidden element could be easily override using CSS. Let's say:

```css
.foobar[hidden] {
  display: flex;
  max-height: 0;
}
```

Then, it's possible to check the end of the transition on the element using `e.target === e.currentTarget` and set `display: none;` to hide it from the screen readers.

**Comment by Paul-Hebert** [comment]
Hey @robsonsobral interesting idea! I'm not 100% sure I follow. Could you provide a more complete code example? How would the `display: none;` be applied?

(FWIW, these days I'd probably default to using CSS animations instead since they work from `display: none;` I should really write a follow-up article and add a note to this library when I find some time at work.)

**Comment by robsonsobral** [comment]
I'm sorry! I should have been clearer.

Let's start by the easier part.

The easier way to check the whether the event occurred on the element you added the event listener or not is to check the `currentEvent` property of it. You don't need to save the element listener. From [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget), with emphasis added:

> The currentTarget read-only property of the [Event](https://developer.mozilla.org/en-US/docs/Web/API/Event) interface identifies the current target for the event, as the event traverses the DOM. **It always refers to the element to which the event handler has been attached**, as opposed to [Event.target](https://developer.mozilla.org/en-US/docs/Web/API/Event/target), which identifies the element on which the event occurred and which may be its descendant.

Example:

```js
  /**
   * An event listener to add `hidden` after our animations complete.
   * This listener will remove itself after completing.
   */
  const listener = e => {
    // Confirm `transitionend` was called on  our `element` and didn't bubble
    // up from a child element.
    if (e.target === e.currentTarget) {
      applyHiddenAttributes();

      e.currentTarget.removeEventListener('transitionend', listener);
    }
  };
```

---

Now the fun part! Let's throw out all I just did.

Some devs hate the `[hidden]` attribute because it can be easily override by CSS. So, the recommendation is to have on your CSS reset:

```css
[hidden] {
  display: none !important;
}
```

However, I think this is the best part. In the case of your article:

```css
.Drawer {
  background: #eee;
  box-shadow: -3px 0px 5px 0px rgba(0,0,0,0.6);  
  
  /* Give our drawer a base width */
  width: 100%;

  /* Position the drawer on the right edge of the screen */
  position: fixed;
  bottom: 0;
  right: 0;
  top: 0;

  /* Transition our horizontal slide */
  transition: transform ease-out 0.3s;
  
  text-align: center;

  /* Slide the drawer back in when it's "open" */
  transform: translateX(0);
}

.Drawer[hidden] {
  display: flex !important;  /* stylelint-disable-line declaration-no-important */
  /* Slide the drawer _past_ the right edge of the screen */
  transform: translateX(100%);
}
```

You just need to override the `display` for the browser _to know_ the element exists. [In action](https://codepen.io/robsonsobral/pen/JjMREwr).

**Comment by Paul-Hebert** [comment]
Got it, thanks @robsonsobral 

My concern would be that if the element is hidden using `transform`/`max-height`/`opacity` but its `display` is still set to `flex`, then the element will not be hidden for screen reader users or other users of assistive technology.

This could be confusing for these users since they're able to interact with content which is meant to be hidden in the UI. In general I strive to provide an [equivalent experience](https://www.smashingmagazine.com/2020/05/equivalent-experiences-part1/) for [screen reader](https://www.afb.org/blindness-and-low-vision/using-technology/assistive-technology-products/screen-readers) users, and so it's important to me that elements be hidden for them those elements are hidden for other users.

This is why the article and this library makes sure that hidden elements are using a `display` property which will remove them from the accessibility tree, and hide them from all users. 

Let me know if I'm misunderstanding or if you have any follow-up questions/thoughts!

**Comment by robsonsobral** [comment]
I agree! Totally! That's the reason I opened this issue. I guess we can simplify things together. To mix both approaches.

Maybe to set `visibility: hidden` after the transition end? Or force the `display: none;` then? `aria-hidden`? I don't know. What I know is that my code is easier than yours to implement and to maintain, while yours respect a11y. Wouldn't be great if we could have a drop-in solution? Just grab the JS, drop it in there and let's have a beer?

**Comment by Paul-Hebert** [comment]
Haha, yeah for sure!

In this case `visibility: hidden` combined with absolute positioning might work well since `visibility: hidden` will remove the element from the accessibility tree and absolute positioning keeps the drawer from taking up space in the document flow.

In other scenarios where the element is in the normal document flow, then `visibility: hidden` wouldn't work because the element would still take up the same space in the DOM.

My goal with this library was to make an easy drop-in solution, but it still requires some setup with your CSS. I'm open to ideas for how to streamline this further!

**Comment by robsonsobral** [comment]
We don't need the `position: absolute;`. The "technique" used to hide the element stays in the charge of the developer.

Thinking out loud here!

We need to "detect" when the transition ended and then apply `visibility` or `display`. I prefer `visibility` as it is way less used than `display`. It would avoid conflicts.

Maybe using `aria-hidden`?

**Comment by Paul-Hebert** [comment]
Hey @robsonsobral , the problem with using `visibility` is that an element with `visibility: hidden` still takes up space in the DOM, so it's not actually removed from the document flow. Therefore this only works if other CSS styles are used to remove the element from the document flow (e.g. absolute positioning)

>We need to "detect" when the transition ended and then apply visibility or display. 

This is how the library works now. It uses event listeners to listen for the `transitionend` event and then [manually toggle the display property](https://github.com/cloudfour/transition-hidden-element/blob/master/src/index.js#L66) or an equivalent class/attribute

**Comment by robsonsobral** [comment]
I need to be clearer...

My point is: let the CSS take care of how the element is moved or removed and make the JS only responsible to hide the element to the screen readers. I'm thinking on how to use your lib to take care of this part.

Again, thinking out loud...

```js
const hidableElms = document.querySelectorAll('[hidden]');

Array.from(hidableElms).forEach((i)=>{
  i.addEventListener('transitionend', (({ target, currentTarget })=>{
    if (target !== currentTarget) return;
    
    if (target.getAttribute('aria-hidden').value === "true") {
      target.setAttribute("aria-hidden", "false");
    } else {
      target.setAttribute("aria-hidden", "true");
    }
  }));
});
```

```css
[hidden][aria-hidden='true'] {
  visibility: hidden;
}
```

I know, I know... It's too rough!
